site_name: Gabriel Fior
site_url: https://gabrielfior.gitlab.io
nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
theme: material

plugins:
  - blogging:
      dirs: # The directories to be included
        - projects
        
      size: 5
      time_format: '%Y-%m-%d' # The format used to display the time
      meta_time_format: '%Y-%m-%d' # The format used to parse the time from meta
      features:
        tags: {}